# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'MPN-150-month-emplea.do(2ab46f86-a176-4fc7-9376-92e54bbad732)'
    Action: 'Restart Azure App Service'
    WebAppName: 'emplea-do-prod'
    SpecifySlotOrASE: true
    ResourceGroupName: 'emplea-do-east2'
    Slot: 'production'
